name: CI - Build and Test

on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Send Discord Notification (Success)
        if: success()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ env.DISCORD_WEBHOOK }}
          message: ":white_check_mark: CI build passed on `${{ github.ref }}` by ${{ github.actor }}"

      - name: Send Discord Notification (Failure)
        if: failure()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ env.DISCORD_WEBHOOK }}
          message: ":x: CI build failed on `${{ github.ref }}` by ${{ github.actor }}"
