name: CI - SpringBoot  Build and Test

on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install --batch-mode

      - name: Send Discord Notification (Success)
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ env.DISCORD_WEBHOOK }}
        with:
          args: |
            ✅ Build succeeded — SpringBoot-Test
            🔀 Branch: ${{ github.ref_name }}
            👤 Triggered by: ${{ github.actor }}
            🔗 Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send Discord Notification (Failure)
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ env.DISCORD_WEBHOOK }}
        with:
          args: |
            ❌ Build failed — SpringBoot-Test
            🔀 Branch: ${{ github.ref_name }}
            👤 Triggered by: ${{ github.actor }}
            🔗 Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}