name: Reusable - SonarCloud Analysis for SpringBoot

on:
  workflow_call:
    inputs:
      projectBaseDir:
        required: false
        type: string
        default: "."
    secrets:
      SONAR_TOKEN:
        required: true
      DISCORD_WEBHOOK:
        required: true

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        run: |
          mvn -f ${{ inputs.projectBaseDir }}/pom.xml verify sonar:sonar \
            -Dsonar.projectKey=genzitizens_${{ github.event.repository.name }} \
            -Dsonar.organization=genzitizens \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN
      - name: Check for Analysis Completion and Notify Discord
        run: |
          PROJECT_KEY="genzitizens_${{ github.event.repository.name }}"

          echo "Waiting for SonarQube/SonarCloud analysis to finalize..."

          for i in {1..10}; do
            ANALYSIS=$(curl -s -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/project_analyses/search?project=$PROJECT_KEY")
            STATUS=$(echo "$ANALYSIS" | jq -r '.analyses[0].status // empty')

            if [ "$STATUS" == "SUCCESS" ]; then
              echo "Analysis complete!"
              break
            fi

            echo "Analysis not ready yet. Waiting..."
            sleep 5
          done

          # Always send Discord notification after analysis completion
          PAYLOAD="{
            \"content\": \"✅ SonarCloud Analysis Completed!\nPlease check: https://sonarcloud.io/project/overview?id=${PROJECT_KEY}\"
          }"

          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"