# .github/workflows/sonarcloud.yml
name:  SonarCloud Analysis for SpringBoot

on:
  workflow_call:
    inputs:
      projectBaseDir:
        required: false
        type: string
        default: '.'
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        run: |
          mvn -f ${{ inputs.projectBaseDir }}/pom.xml verify sonar:sonar \
            -Dsonar.projectKey=genzitizens_${{ github.event.repository.name }} \
            -Dsonar.organization=genzitizens \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
