name: Push to GHCR

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: true
      DISCORD_WEBHOOK:
        required: true
      GHCR_ORG:
        required: true

jobs:
  ghcr-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Make Maven Wrapper Executable
        run: chmod +x ./mvnw

      - name: Get Git SHA
        id: get_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Image using Spring Boot
        run: |
          ./mvnw spring-boot:build-image \
            -Dspring-boot.build-image.imageName=ghcr.io/${{ secrets.GHCR_ORG }}/${{ inputs.image_name }}:latest

      - name: Tag SHA Version
        run: |
          docker tag ghcr.io/${{ secrets.GHCR_ORG }}/${{ inputs.image_name }}:latest \
                     ghcr.io/${{ secrets.GHCR_ORG }}/${{ inputs.image_name }}:${{ steps.get_sha.outputs.sha_short }}

      - name: Docker Login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u mediocreasian --password-stdin

      - name: Docker Push
        run: |
          docker push ghcr.io/${{ secrets.GHCR_ORG }}/${{ inputs.image_name }}:latest
          docker push ghcr.io/${{ secrets.GHCR_ORG }}/${{ inputs.image_name }}:${{ steps.get_sha.outputs.sha_short }}

      - name: Send Discord Notification (Success)
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ✅ Docker image pushed — ${{ inputs.image_name }}
            🔀 Branch: ${{ github.ref_name }}
            👤 Triggered by: ${{ github.actor }}
            🔗 Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send Discord Notification (Failure)
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            ❌ Docker push failed — ${{ inputs.image_name }}
            🔀 Branch: ${{ github.ref_name }}
            👤 Triggered by: ${{ github.actor }}
            🔗 Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
